---
title: "RRBS Sample Metadata"
author: "Annat Haber"
date: '`r Sys.Date()`'
output:
  html_document:
    toc: true
    code_folding: hide
    df_print: "kable"
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(message=FALSE, warning=FALSE, cache = FALSE)
```

```{r libraries}
suppressPackageStartupMessages({
  library(synapser)
  library(tidyverse)
})
```

Sample size included in the RRBS analysis by sex, age, and genotype.  
```{r metadata}
meta <- read_csv("data/RRBS/RRBS_sample_metadata.csv", col_types = cols(.default = "c")) %>%
  mutate(genotype = recode(genotype, "-/-"="TT", "-/+"="CT", "+/+"="CC"),
         group = paste(genotype, age, sex, sep="_"),
         sample_id = str_pad(tag_id, 5, pad = "0")) %>%
  arrange(sample_id)

# add treatment vector for methylKit operations
meta <- left_join(meta,
              data.frame(treatment=0:11, group=unique(meta$group)),
              by="group")

meta %>% 
  group_by(sex, age, genotype) %>%
  summarise(n=n())
```

Saving metadata and uploading to [synapse](https://www.synapse.org/#!Synapse:syn25174517).
Genotype is recoded as "-/-"="TT"; "-/+"="CT"; "+/+"="CC"
```{r output, results='hide'}
write_csv(meta, file="output/RRBS/RRBS_sample_meta.csv")

synLogin() 
file <- File("output/RRBS/RRBS_sample_meta.csv",
             contentType = "text/plain",
             description = "sample metadata recoded",
             parent = "syn25174486")

provenance <- Activity(executed = "https://github.com/TheJacksonLaboratory/MTHFR_C667T/blob/master/RRBS_0_Sample_Metadata.Rmd")
```